=== B-Beny/IG1TYM_XMLGyak/XMLTaskIG1TYM/XSDIG1TYM.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tetoTipus">
        <xs:restriction base="xs:token">
            <xs:enumeration value="van" />
            <xs:enumeration value="nincs" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Egyszerű típusok - Felépítés -->

    <xs:element name="gepjarmu-felepites">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="auto" maxOccurs="unbounded" />
                <xs:element name="gyarto" maxOccurs="unbounded" />
                <xs:element name="modell" maxOccurs="unbounded" />
                <xs:element name="motor" maxOccurs="unbounded" />
                <xs:element name="gyartja" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!-- Kulcsok -->
        <xs:key name="auto_kulcs">
            <xs:selector xpath="auto" />
            <xs:field xpath="@alvazszam" />
        </xs:key>

        <xs:key name="gyarto_kulcs">
            <xs:selector xpath="gyarto" />
            <xs:field xpath="@adoszam" />
        </xs:key>

        <xs:key name="modell_kulcs">
            <xs:selector xpath="modell" />
            <xs:field xpath="@nev" />
        </xs:key>

        <xs:key name="motor_kulcs">
            <xs:selector xpath="motor" />
            <xs:field xpath="@motorkod" />
        </xs:key>
        
        <!-- Idegen kulcsok -->

        <xs:keyref refer="auto_kulcs" name="auto_idegen_kulcs">
            <xs:selector xpath="gyartja" />
            <xs:field xpath="@Aut_Gyart_Aut" />
        </xs:keyref>

        <xs:keyref refer="gyarto_kulcs" name="gyarto_idegen_kulcs">
            <xs:selector xpath="gyartja" />
            <xs:field xpath="@Aut_Gyart_Gyart" />
        </xs:keyref>

        <xs:keyref refer="modell_kulcs" name="modell_auto_idegen_kulcs">
            <xs:selector xpath="auto" />
            <xs:field xpath="@Aut_Mod" />
        </xs:keyref>

        <xs:keyref refer="auto_kulcs" name="auto_motor_idegen_kulcs">
            <xs:selector xpath="motor" />
            <xs:field xpath="@Mot_Aut" />
        </xs:keyref>

        <xs:keyref refer="gyarto_kulcs" name="gyarto_motor_idegen_kulcs">
            <xs:selector xpath="motor" />
            <xs:field xpath="@Mot_Gyart" />
        </xs:keyref>

    </xs:element>

    <xs:element name="auto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nev" type="xs:string" />
                <xs:element name="tomeg" type="xs:integer" />
                <xs:element name="szin" type="xs:string" maxOccurs="unbounded" />
                <xs:element name="teljesitmeny" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gyarto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nev" type="xs:string" />
                <xs:element name="cim">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="orszag" type="xs:string" />
                            <xs:element name="iranyitoszam" type="xs:integer" />
                            <xs:element name="telepules" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="modell">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ajtok_szama" type="xs:integer" />
                <xs:element name="csomagtarto_meret" type="xs:integer" />
                <xs:element name="lehajthato_teto" type="tetoTipus" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="motor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alaprajz">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hengerurtartalom" type="xs:integer" />
                            <xs:element name="hengerelrendezes" type="xs:integer" />
                            <xs:element name="hengerek_szama" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uzemanyag" type="xs:string" maxOccurs="unbounded" />
                <xs:element name="nyomatek" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="gyartja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="evjarat" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== B-Beny/IG1TYM_XMLGyak/XMLTaskIG1TYM/XMLIG1TYM.xml
<?xml version="1.0" encoding="UTF-8"?>

<gepjarmu-felepites xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XSDIG1TYM.xsd">
    
    <!-- Autók -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->
    <auto alvazszam="01" Aut_Mod="3-Door Hatchback">
        <nev>Sprinter Trueno GT-Apex</nev>
        <tomeg>970</tomeg>
        <szin>Panda</szin>
        <szin>Yellow</szin>
        <szin>Wine Metallic</szin>
        <szin>White Metallic</szin>
        <teljesitmeny>123 HP</teljesitmeny>
    </auto>

    <auto alvazszam="02" Aut_Mod="5-Door Hatchback">
        <nev>206 Profil</nev>
        <tomeg>1100</tomeg>
        <szin>Indigo Blue</szin>
        <szin>Rogue Red</szin>
        <szin>Vert Green</szin>
        <teljesitmeny>60 HP</teljesitmeny>
    </auto>

    <auto alvazszam="03" Aut_Mod="Coupe">
        <nev>Skyline GTR R34</nev>
        <tomeg>1560</tomeg>
        <szin>Bayside Blue</szin>
        <szin>Midnight Purple</szin>
        <szin>Millenium Jade</szin>
        <szin>Lightning Yellow</szin>
        <szin>Active Red</szin>
        <szin>Pearl White</szin>
        <teljesitmeny>276 HP</teljesitmeny>
    </auto>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Gyártók -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->
    <gyarto adoszam="123">
        <nev>Toyota</nev>
        <cim>
            <orszag>Japán</orszag>
            <iranyitoszam>1234</iranyitoszam>
            <telepules>Toiota</telepules>
        </cim>
    </gyarto>

    <gyarto adoszam="124">
        <nev>Peugeot</nev>
        <cim>
            <orszag>Franciaország</orszag>
            <iranyitoszam>1235</iranyitoszam>
            <telepules>Párizs</telepules>
        </cim>
    </gyarto>

    <gyarto adoszam="125">
        <nev>Nissan</nev>
        <cim>
            <orszag>Japán</orszag>
            <iranyitoszam>1326</iranyitoszam>
            <telepules>Yokohama</telepules>
        </cim>
    </gyarto>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Modellek -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->
    <modell nev="3-Door Hatchback">
        <ajtok_szama>3</ajtok_szama>
        <csomagtarto_meret>280</csomagtarto_meret>
        <lehajthato_teto>Nincs</lehajthato_teto>
    </modell>

    <modell nev="5-Door Hatchback">
        <ajtok_szama>5</ajtok_szama>
        <csomagtarto_meret>237</csomagtarto_meret>
        <lehajthato_teto>Nincs</lehajthato_teto>
    </modell>

    <modell nev="Coupe">
        <ajtok_szama>2</ajtok_szama>
        <csomagtarto_meret>315</csomagtarto_meret>
        <lehajthato_teto>Nincs</lehajthato_teto>
    </modell>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Motorok -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->
    <motor motorkod="4A-GE" Mot_Aut="01" Mot_Gyart="123">
        <alaprajz>
            <hengerurtartalom>1598</hengerurtartalom>
            <hengerelrendezes>I</hengerelrendezes>
            <hengerek_szama>4</hengerek_szama>
        </alaprajz>
        <uzemanyag>95 Benzin E10</uzemanyag>
        <uzemanyag>98 Benzin E5</uzemanyag>
        <uzemanyag>100 Benzin E5</uzemanyag>
        <nyomatek>92 kW</nyomatek>
    </motor>

    <motor motorkod="TU1JP" Mot_Aut="02" Mot_Gyart="124">
        <alaprajz>
            <hengerurtartalom>1110</hengerurtartalom>
            <hengerelrendezes>I</hengerelrendezes>
            <hengerek_szama>4</hengerek_szama>
        </alaprajz>
        <uzemanyag>95 Benzin E10</uzemanyag>
        <uzemanyag>98 Benzin E5</uzemanyag>
        <uzemanyag>100 Benzin E5</uzemanyag>
        <nyomatek>44 kW</nyomatek>
    </motor>

    <motor motorkod="RB26DETT" Mot_Aut="03" Mot_Gyart="125">
        <alaprajz>
            <hengerurtartalom>2600</hengerurtartalom>
            <hengerelrendezes>I</hengerelrendezes>
            <hengerek_szama>6</hengerek_szama>
        </alaprajz>
        <uzemanyag>95 Benzin E10</uzemanyag>
        <uzemanyag>98 Benzin E5</uzemanyag>
        <uzemanyag>100 Benzin E5</uzemanyag>
        <nyomatek>206 kW</nyomatek>
    </motor>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Gyártja kapcsoló -->
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->
    <gyartja Aut_Gyart_Aut="01" Aut_Gyart_Gyart="123">
        <evjarat>1986</evjarat>
    </gyartja>

    <gyartja Aut_Gyart_Aut="02" Aut_Gyart_Gyart="124">
        <evjarat>2000</evjarat>
    </gyartja>

    <gyartja Aut_Gyart_Aut="03" Aut_Gyart_Gyart="125">
        <evjarat>2002</evjarat>
    </gyartja>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - -->

</gepjarmu-felepites>
